---
abstract: 'N-dimensional histogramming library'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Histogram
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0
  Data::Dumper: 0
  ExtUtils::ParseXS: 2.21
  File::Spec: 0
  Getopt::Long: 0
  JSON::XS: 0
  Test::More: 0.94
version: 1.02
